import {
  Archive,
  ArchiveRestore,
  ArrowDown,
  ArrowRight,
  ArrowUp,
  Award,
  BadgeCheck,
  Blocks,
  Bookmark,
  BookOpen,
  BriefcaseBusiness,
  Building2,
  Calendar,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  CircleAlert,
  CircleCheck,
  CircleDot,
  Command,
  Copy,
  DatabaseBackup,
  Download,
  EllipsisVertical,
  ExternalLink,
  Eye,
  EyeOff,
  FileOutput,
  FileText,
  GraduationCap,
  GripVertical,
  Heading,
  HeartHandshake,
  History,
  Info,
  Keyboard,
  Languages,
  Layers,
  LayoutDashboard,
  LayoutGrid,
  LayoutTemplate,
  Link,
  ListFilter,
  LoaderCircle,
  Lock,
  LogOut,
  Menu,
  Merge,
  Mic,
  Monitor,
  Moon,
  PanelLeftClose,
  PanelLeftOpen,
  Paperclip,
  Pencil,
  Plus,
  RotateCw,
  Rows3,
  Ruler,
  Search,
  ShieldCheck,
  SlidersHorizontal,
  Sparkles,
  Sun,
  Table2,
  Tag,
  Target,
  TrendingUp,
  TriangleAlert,
  Undo2,
  UserRound,
  Wrench,
  X,
} from "lucide-react";

// Keyed by what the icon means here, never by what the drawing is: swapping the
// glyph for a point is one line, and a screen never names a vendor's icon.
export const GLYPHS = {
  overview: LayoutDashboard,
  profile: UserRound,
  record: BriefcaseBusiness,
  point: CircleDot,
  tag: Tag,
  section: Heading,
  resume: FileText,
  organisation: Building2,
  data: DatabaseBackup,
  search: Search,
  signOut: LogOut,

  add: Plus,
  edit: Pencil,
  archive: Archive,
  restore: ArchiveRestore,
  confirm: Check,
  cancel: X,
  close: X,
  more: EllipsisVertical,
  download: Download,
  upload: FileOutput,
  copy: Copy,
  merge: Merge,
  revert: Undo2,
  refresh: RotateCw,
  external: ExternalLink,
  drag: GripVertical,
  filter: ListFilter,
  settings: SlidersHorizontal,

  chevronDown: ChevronDown,
  chevronUp: ChevronUp,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  moveUp: ArrowUp,
  moveDown: ArrowDown,
  forward: ArrowRight,
  menu: Menu,
  collapse: PanelLeftClose,
  expand: PanelLeftOpen,
  rows: Rows3,
  grid: LayoutGrid,

  warning: TriangleAlert,
  error: CircleAlert,
  success: CircleCheck,
  info: Info,
  pending: LoaderCircle,
  private: Lock,
  visible: Eye,
  hidden: EyeOff,

  lint: ShieldCheck,
  budget: Ruler,
  match: Target,
  history: History,
  variants: Layers,
  metric: TrendingUp,
  evidence: Paperclip,
  link: Link,
  field: Table2,
  date: Calendar,
  template: LayoutTemplate,
  highlight: Sparkles,

  experience: BriefcaseBusiness,
  education: GraduationCap,
  project: Blocks,
  skill: Wrench,
  certification: BadgeCheck,
  publication: BookOpen,
  award: Award,
  language: Languages,
  volunteering: HeartHandshake,
  speaking: Mic,
  customEntry: Bookmark,

  light: Sun,
  dark: Moon,
  system: Monitor,
  command: Command,
  keyboard: Keyboard,
} as const;

export type GlyphName = keyof typeof GLYPHS;
