import { z } from "zod";

// UUIDv7 specifically (data-model.md #3.1). Accepting any version would let an
// identifier generated by the wrong helper through the boundary, where it
// silently costs the index locality the choice was made for.
export const uuidSchema = z.uuid({ version: "v7" }).brand<"Uuid">();

export type Uuid = z.infer<typeof uuidSchema>;
